namespace Tron4Biz.Tests.Crypto;

public static class TestVectors
{
    public static class Bip39
    {
        public static readonly string[] EnglishWordlist = new[]
        {
            "abandon", "ability", "able", "about", "above", "absent", "absorb", "abstract", "absurd", "abuse",
            "access", "accident", "account", "accuse", "achieve", "acid", "acoustic", "acquire", "across", "act",
            "action", "actor", "actress", "actual", "adapt", "add", "addict", "address", "adjust", "admit",
            "adult", "advance", "advice", "aerobic", "affair", "afford", "afraid", "again", "age", "agent",
            "agree", "ahead", "aim", "air", "airport", "aisle", "alarm", "album", "alcohol", "alert",
            "alien", "all", "alley", "allow", "almost", "alone", "alpha", "already", "also", "alter",
            "always", "amateur", "amazing", "among", "amount", "amused", "analyst", "anchor", "ancient", "anger",
            "angle", "angry", "animal", "ankle", "announce", "annual", "another", "answer", "antenna", "antique",
            "anxiety", "any", "apart", "apology", "appear", "apple", "approve", "april", "arch", "arctic",
            "area", "arena", "argue", "arm", "armed", "armor", "army", "around", "arrange", "arrest",
            "arrive", "arrow", "art", "artefact", "artist", "artwork", "ask", "aspect", "assault", "asset",
            "assist", "assume", "asthma", "athlete", "atom", "attack", "attend", "attitude", "attract", "auction",
            "audit", "august", "aunt", "author", "auto", "autumn", "average", "avocado", "avoid", "awake",
            "aware", "away", "awesome", "awful", "awkward", "axis", "baby", "bachelor", "bacon", "badge",
            "bag", "balance", "balcony", "ball", "bamboo", "banana", "banner", "bar", "barely", "bargain",
            "barrel", "base", "basic", "basket", "battle", "beach", "bean", "beauty", "because", "become",
            "beef", "before", "begin", "behave", "behind", "believe", "below", "belt", "bench", "benefit",
            "best", "betray", "better", "between", "beyond", "bicycle", "bid", "bike", "bind", "biology",
            "bird", "birth", "bitter", "black", "blade", "blame", "blanket", "blast", "bleak", "bless",
            "blind", "blood", "blossom", "blouse", "blue", "blur", "blush", "board", "boat", "body",
            "boil", "bomb", "bone", "bonus", "book", "boost", "border", "boring", "borrow", "boss",
            "bottom", "bounce", "box", "boy", "bracket", "brain", "brand", "brass", "brave", "bread",
            "breeze", "brick", "bridge", "brief", "bright", "bring", "brisk", "broccoli", "broken", "bronze",
            "broom", "brother", "brown", "brush", "bubble", "buddy", "budget", "buffalo", "build", "bulgur",
            "bullet", "bundle", "bunker", "burden", "burger", "burst", "bus", "business", "busy", "butter",
            "buyer", "buzz", "cabbage", "cabin", "cable", "cactus", "cage", "cake", "call", "calm",
            "camera", "camp", "can", "canal", "cancel", "candy", "cannon", "canoe", "canvas", "canyon",
            "capable", "capital", "captain", "car", "carbon", "card", "cargo", "carpet", "carry", "cart",
            "case", "cash", "casino", "castle", "casual", "cat", "catalog", "catch", "category", "cattle",
            "caught", "cause", "caution", "cave", "ceiling", "celery", "cement", "census", "century", "cereal",
            "certain", "chair", "chalk", "champion", "change", "chaos", "chapter", "charge", "chase", "chat",
            "cheap", "check", "cheese", "chef", "cherry", "chest", "chicken", "chief", "child", "chimney",
            "choice", "choose", "chronic", "chuckle", "chunk", "churn", "cigar", "cinnamon", "circle", "citizen",
            "city", "civil", "claim", "clap", "clarify", "claw", "clay", "clean", "clerk", "clever",
            "click", "client", "cliff", "climb", "clinic", "clip", "clock", "clog", "close", "cloth",
            "cloud", "clown", "club", "clump", "cluster", "clutch", "coach", "coast", "coconut", "code",
            "coffee", "coil", "coin", "collect", "color", "column", "combine", "come", "comfort", "comic",
            "common", "company", "concert", "conduct", "confirm", "congress", "connect", "consider", "control", "convince",
            "cook", "cool", "copper", "copy", "coral", "core", "corn", "correct", "cost", "cotton",
            "couch", "country", "couple", "course", "cousin", "cover", "coyote", "crack", "cradle", "craft",
            "cram", "crane", "crash", "crater", "crawl", "crazy", "cream", "credit", "creek", "crew",
            "cricket", "crime", "crisp", "critic", "crop", "cross", "crouch", "crowd", "crucial", "cruel",
            "cruise", "crumble", "crunch", "crush", "cry", "crystal", "cube", "culture", "cup", "cupboard",
            "curious", "current", "curtain", "curve", "cushion", "custom", "cute", "cycle", "dad", "damage",
            "damp", "dance", "danger", "daring", "dash", "daughter", "dawn", "day", "deal", "debt",
            "decade", "december", "decide", "decline", "decorate", "decrease", "deer", "defense", "define", "defy",
            "degree", "delay", "deliver", "demand", "demise", "denial", "dentist", "deny", "depart", "depend",
            "deposit", "depth", "deputy", "derive", "describe", "desert", "design", "desk", "despair", "destroy",
            "detail", "detect", "develop", "device", "devote", "diagram", "dial", "diamond", "diary", "dice",
            "diesel", "diet", "differ", "digital", "dignity", "dilemma", "dinner", "dinosaur", "direct", "dirt",
            "disagree", "discover", "disease", "dish", "dismiss", "disorder", "display", "distance", "divert", "divide",
            "divorce", "dizzy", "doctor", "document", "dog", "doll", "dolphin", "domain", "donate", "donkey",
            "donor", "door", "dose", "double", "dove", "draft", "dragon", "drama", "drastic", "draw", "dream",
            "dress", "drift", "drill", "drink", "drip", "drive", "drop", "drum", "dry", "duck", "dumb",
            "dune", "during", "dust", "dutch", "duty", "dwarf", "dynamic", "eager", "eagle", "early", "earn",
            "earth", "easily", "east", "easy", "echo", "ecology", "economy", "edge", "edit", "educate", "effort",
            "egg", "either", "elbow", "elder", "electric", "elegant", "element", "elephant", "elevator", "elite",
            "else", "embark", "embody", "embrace", "emerge", "emotion", "employ", "empower", "empty", "enable", "enact",
            "end", "endless", "endorse", "enemy", "energy", "enforce", "engage", "engine", "enhance", "enjoy", "enlist",
            "enough", "enrich", "enroll", "ensure", "enter", "entire", "entry", "envelope", "episode", "equal", "equip",
            "era", "erase", "erode", "erosion", "error", "erupt", "escape", "essay", "essence", "estate", "eternal",
            "ethics", "evidence", "evil", "evoke", "evolve", "exact", "example", "excess", "exchange", "excite", "exclude",
            "excuse", "execute", "exercise", "exhaust", "exhibit", "exile", "exist", "exit", "exotic", "expand", "expect",
            "expire", "explain", "expose", "express", "extend", "extra", "eye", "eyebrow", "fabric", "face", "faculty",
            "fade", "faint", "faith", "fall", "false", "fame", "family", "famous", "fan", "fancy", "fantasy",
            "farm", "fashion", "fat", "fatal", "father", "fatigue", "fault", "favorite", "feature", "february", "federal",
            "fee", "feed", "feel", "female", "fence", "festival", "fetch", "fever", "few", "fiber", "fiction",
            "field", "figure", "file", "film", "filter", "final", "find", "fine", "finger", "finish", "fire",
            "firm", "first", "fiscal", "fish", "fit", "fitness", "fix", "flag", "flame", "flash", "flat",
            "flavor", "flee", "flight", "flip", "float", "flock", "floor", "flower", "fluid", "flush", "fly",
            "foam", "focus", "fog", "foil", "fold", "follow", "food", "foot", "force", "forest", "forget", "fork",
            "fortune", "forum", "forward", "fossil", "foster", "found", "fox", "fragile", "frame", "frequent", "fresh",
            "friend", "fringe", "frog", "front", "frost", "frown", "frozen", "fruit", "fuel", "fun", "funny",
            "furnace", "fury", "future", "gadget", "gain", "galaxy", "gallery", "game", "gap", "garage", "garbage",
            "garden", "garlic", "garment", "gas", "gasp", "gate", "gather", "gauge", "gaze", "general", "genius",
            "genre", "gentle", "genuine", "gesture", "ghost", "giant", "gift", "giggle", "ginger", "giraffe", "girl",
            "give", "glad", "glance", "glare", "glass", "gleam", "globe", "gloom", "glory", "glove", "glow",
            "goal", "goat", "goddess", "gold", "golf", "good", "goose", "gorgeous", "gown", "grab", "grace",
            "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grateful", "gravity", "great",
            "green", "greet", "grief", "grill", "grind", "grip", "groan", "grocery", "groom", "gross", "group",
            "grow", "growth", "guard", "guess", "guest", "guide", "guilt", "guitar", "gun", "gust", "gutter",
            "habit", "hair", "half", "hammer", "hamster", "hand", "happy", "harbor", "hard", "harsh", "harvest",
            "haste", "hat", "have", "hawk", "hazard", "head", "health", "heart", "heavy", "hedgehog", "height",
            "hello", "helmet", "help", "helpful", "her", "here", "hero", "hidden", "high", "hill", "hint",
            "hip", "hire", "history", "hold", "hole", "holiday", "hollow", "home", "honey", "honor", "hope",
            "horizon", "horn", "horror", "horse", "hospital", "hotel", "hour", "hover", "hub", "huge", "human",
            "humble", "humor", "hundred", "hunger", "hunt", "hurdle", "hurry", "hurt", "husband", "hybrid", "ice",
            "icon", "idea", "ideal", "identity", "idle", "ignore", "ill", "illegal", "illness", "image", "imitate",
            "immense", "immune", "impact", "impose", "improve", "impulse", "inch", "include", "income", "increase", "index",
            "indicate", "indoor", "industry", "infant", "inflict", "inform", "ink", "innate", "innocence", "input", "inquiry",
            "insect", "inside", "inspire", "install", "intact", "interest", "into", "invest", "invite", "involve", "iron",
            "island", "isolate", "issue", "item", "ivory", "jacket", "jaguar", "jar", "jazz", "jealous", "jeans",
            "jelly", "jewel", "job", "join", "joke", "jolly", "jolly", "journey", "joy", "judge", "juice",
            "jump", "junior", "junk", "just", "kaleidoscope", "kangaroo", "keep", "kennel", "kept", "kick", "kidney",
            "kind", "king", "kiss", "kitchen", "kite", "kitten", "kiwi", "knee", "knife", "knock", "knot", "know",
            "knowledge", "koala", "label", "labor", "lace", "ladder", "lady", "lake", "lamp", "land", "landscape",
            "lane", "language", "laptop", "large", "later", "latin", "laugh", "laundry", "lava", "law", "lawn",
            "lawsuit", "layer", "lazy", "lead", "leaf", "learn", "lease", "least", "leave", "legal", "lemon",
            "level", "lever", "liberty", "library", "license", "life", "lift", "light", "like", "limb", "limit",
            "linear", "linen", "lion", "lips", "list", "live", "liver", "living", "llama", "load", "loan", "lobby",
            "local", "lodge", "logic", "loose", "lose", "loss", "lost", "lot", "lotus", "loud", "lounge", "love",
            "loyal", "luck", "lucky", "lumber", "lunar", "lunch", "lyric", "machine", "mad", "made", "magic",
            "magnet", "maid", "mail", "main", "maintain", "major", "make", "mammal", "man", "manage", "mandate",
            "mango", "manner", "mansion", "many", "maple", "march", "margin", "marine", "market", "marriage", "mask",
            "mass", "master", "match", "mate", "material", "math", "mauve", "matter", "maximum", "maybe", "mayor",
            "me", "meal", "mean", "meaning", "measure", "meat", "mechanic", "medal", "media", "melon", "melody",
            "melt", "memo", "mention", "mentor", "mercy", "merge", "merit", "merry", "mesh", "message", "metal",
            "meter", "method", "microphone", "middle", "midnight", "might", "milk", "meter", "million", "mind", "mine",
            "mint", "minute", "miracle", "mirror", "misery", "miss", "mistake", "mix", "mixed", "mixture", "mobile",
            "model", "modify", "moment", "monkey", "monster", "month", "moon", "moral", "more", "morning", "mosquito",
            "mother", "motion", "motor", "mould", "mount", "mouse", "mouth", "movie", "much", "muffin", "mule",
            "multiply", "muscle", "museum", "mushroom", "music", "must", "mutual", "myself", "mystery", "myth", "naive",
            "name", "nanny", "narcis", "nation", "native", "nature", "near", "neck", "need", "negative", "negotiate",
            "neighbor", "neither", "neon", "nephew", "nerve", "nest", "net", "never", "new", "news", "next", "nice",
            "niece", "night", "noble", "noise", "nominee", "none", "noon", "normal", "north", "nose", "notable", "note",
            "nothing", "notice", "notion", "novel", "nurse", "occur", "ocean", "october", "odor", "offer", "office",
            "often", "olive", "olympic", "once", "onion", "online", "only", "open", "opera", "opinion", "oppose",
            "option", "orange", "orbit", "order", "ordinary", "organ", "orient", "original", "orphan", "other", "outer",
            "outcome", "outside", "oval", "oven", "over", "own", "owner", "oxygen", "oyster", "ozone", "paddle",
            "page", "pain", "paint", "pair", "palace", "palm", "panda", "panel", "panic", "paper", "parade",
            "parent", "park", "parrot", "party", "pass", "patch", "patent", "patience", "patient", "pattern", "pause",
            "pay", "peace", "peach", "peacock", "pearl", "penny", "people", "pepper", "perfect", "permit", "person",
            "pet", "phase", "phone", "photo", "phrase", "physical", "piano", "piece", "pilot", "pin", "pineapple",
            "pink", "pioneer", "pipe", "pistol", "pitch", "pizza", "place", "plain", "plan", "plane", "planet",
            "plant", "plate", "play", "please", "pledge", "pluck", "plumb", "plunge", "plus", "pocket", "poem",
            "point", "poison", "polar", "police", "pond", "pony", "pool", "popular", "portion", "position", "possible",
            "post", "pot", "potato", "pouch", "powder", "power", "practice", "praise", "predict", "prefer", "present",
            "preserve", "press", "price", "pride", "primary", "prime", "print", "prior", "prize", "probe", "process",
            "produce", "product", "program", "project", "promote", "proof", "property", "proposal", "propose", "protect", "protein",
            "protest", "provide", "proud", "prove", "proverb", "provide", "pull", "pulp", "pumpkin", "punch", "pupil",
            "purchase", "pure", "purple", "purse", "push", "puzzle", "python", "queen", "query", "quest", "quick",
            "quiet", "quite", "quota", "quote", "rabbit", "raccoon", "race", "rack", "radar", "radio", "rail",
            "rain", "raise", "rally", "ranch", "random", "range", "rapid", "rare", "rash", "rather", "raven", "razor",
            "reach", "react", "read", "ready", "realm", "reap", "rear", "reason", "rebate", "recall", "receive", "recipe",
            "record", "recycle", "reduce", "reflect", "reform", "refuse", "regard", "region", "regret", "regular", "reject",
            "relate", "relax", "release", "relief", "relieve", "rely", "remain", "remark", "remedy", "remember", "remind",
            "remote", "remove", "render", "rent", "rental", "repair", "repeat", "replace", "report", "rescue", "resemble",
            "resist", "resource", "response", "result", "retire", "retreat", "return", "reveal", "review", "reward", "rhino",
            "ridge", "rifle", "right", "rigid", "ring", "riot", "ripple", "rise", "risk", "ritual", "rival",
            "river", "roast", "robin", "robot", "rock", "rocket", "rocky", "romantic", "rose", "roast", "rotate", "rough",
            "round", "route", "royal", "rubber", "rugby", "rude", "ruin", "rule", "run", "runway", "rural",
            "rust", "sad", "saddle", "sadness", "safe", "sail", "saint", "salad", "salmon", "salon", "salsa",
            "salute", "same", "sample", "sand", "satisfy", "satoshi", "sauce", "save", "say", "scale", "scan",
            "scare", "scarce", "scene", "scent", "scheme", "school", "science", "scissors", "scorpion", "scout", "scrap",
            "screen", "script", "scrub", "sea", "search", "season", "seat", "second", "secret", "section", "sector",
            "secure", "seed", "seek", "segment", "select", "sell", "seminar", "senate", "senior", "sense", "sentence",
            "series", "server", "service", "session", "settle", "setup", "seven", "shadow", "shaft", "shallow", "share",
            "shark", "sharp", "shed", "shell", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot",
            "shop", "short", "shoulder", "shove", "shrimp", "shrug", "shuffle", "shy", "sibling", "sick", "siege",
            "sight", "sign", "silent", "silk", "silly", "silver", "similar", "simple", "since", "sing", "singer",
            "single", "sister", "sit", "site", "six", "size", "skate", "sketch", "ski", "skill", "skin",
            "skip", "skirt", "skull", "slam", "slave", "sleep", "slice", "slide", "slight", "slim", "slogan",
            "slot", "slow", "slush", "small", "smart", "smell", "smile", "smoke", "smooth", "snack", "snake",
            "snap", "snare", "snatch", "sneak", "snow", "so", "soap", "soccer", "social", "socket", "soda",
            "sofa", "soft", "software", "soil", "solar", "soldier", "solid", "solution", "solve", "someone", "sorrow",
            "sorry", "sound", "south", "space", "spare", "spark", "speak", "speaker", "special", "speed", "spell",
            "spend", "sphere", "spice", "spider", "spike", "spill", "spin", "spine", "spirit", "split", "spoil",
            "sponsor", "spoon", "sport", "spot", "spray", "spread", "spring", "spy", "squad", "square", "squeeze",
            "stadium", "staff", "stage", "stain", "stair", "stairs", "stake", "stamp", "stand", "staple", "star",
            "start", "state", "station", "status", "stay", "steady", "steak", "steal", "steam", "steel", "steep",
            "steer", "stem", "step", "stew", "stick", "still", "stock", "stomach", "stone", "stool", "store",
            "storm", "story", "stove", "straight", "strain", "strand", "strange", "stranger", "strap", "strategy", "straw",
            "stray", "streak", "stream", "street", "stress", "strict", "stride", "strike", "string", "strip", "stripe",
            "stroke", "strong", "struck", "structure", "struggle", "stuff", "stumble", "style", "subject", "submit", "subtle",
            "subway", "success", "such", "sudden", "suffer", "sugar", "suggest", "suite", "sunny", "super", "superior",
            "serve", "surge", "surprise", "surround", "survey", "suspect", "sustain", "swallow", "swamp", "swear", "sweat",
            "sweep", "sweet", "swift", "swim", "swing", "switch", "sword", "symbol", "symptom", "syrup", "system",
            "table", "tackle", "tactic", "tail", "take", "tale", "talent", "talk", "tank", "tape", "target",
            "task", "taste", "taste", "tattoo", "taxi", "teach", "teacher", "team", "tear", "technical", "technique",
            "technology", "teen", "teeth", "tempo", "tend", "tender", "tennis", "tense", "tenth", "term", "test",
            "testify", "testimony", "text", "thank", "that", "theme", "then", "theory", "therapy", "there", "they",
            "thick", "thief", "thigh", "thing", "think", "third", "thirst", "thirteen", "thirty", "this", "thorough",
            "those", "though", "thought", "thread", "threat", "three", "thrive", "throat", "throne", "through", "throw",
            "thumb", "thunder", "ticket", "tiger", "tight", "tile", "tilt", "timber", "time", "timid", "tiny",
            "tired", "tissue", "title", "toast", "today", "token", "tolerance", "tomato", "tomorrow", "tone", "tongue",
            "tonight", "tool", "tooth", "topic", "torch", "total", "touch", "tough", "tour", "tourist", "tournament",
            "toward", "towards", "tower", "town", "toy", "track", "trade", "traffic", "tragic", "trail", "train",
            "trait", "transfer", "transform", "transit", "trash", "travel", "treat", "treaty", "tree", "tremendous", "trend",
            "trial", "tribe", "trick", "trigger", "trillion", "trim", "trip", "trophy", "tropical", "trouble", "truck",
            "true", "truly", "trumpet", "trust", "truth", "tunnel", "turkey", "turn", "turtle", "twelve", "twenty",
            "twice", "twin", "twist", "two", "type", "typical", "ugly", "ultimate", "umbrella", "unable", "uncle",
            "under", "undergo", "understand", "undo", "unfair", "unfold", "unhappy", "uniform", "union", "unique", "unit",
            "unite", "unity", "universe", "unknown", "unless", "unlike", "unlock", "until", "update", "upgrade", "uphold",
            "upon", "upper", "upset", "urban", "urge", "usage", "use", "used", "useful", "useless", "usual",
            "utility", "vaccine", "vacuum", "vague", "valid", "valley", "value", "valve", "vampire", "van", "vanish",
            "various", "vast", "vault", "venue", "verse", "version", "very", "vessel", "veteran", "viable", "vibrant",
            "vicious", "victory", "video", "view", "village", "vintage", "violin", "virtual", "virus", "visible", "vision",
            "visit", "visual", "vital", "vivid", "vocal", "voice", "void", "volcano", "volume", "vote", "voyage",
            "wage", "wager", "wait", "wake", "walk", "wall", "walnut", "want", "warfare", "warm", "warrior",
            "wash", "wasp", "waste", "watch", "water", "wave", "way", "wealth", "wealthy", "weapon", "wear",
            "weasel", "weather", "web", "wedding", "weekend", "weep", "welcome", "well", "west", "western", "wet",
            "whale", "what", "wheat", "wheel", "when", "where", "which", "while", "whisper", "who", "whole",
            "whose", "wicked", "wide", "width", "wife", "wild", "will", "willing", "willow", "win", "window",
            "wine", "wing", "wing", "wink", "winner", "winter", "wire", "wisdom", "wise", "wish", "witch",
            "withdraw", "within", "without", "witness", "wolf", "woman", "wonder", "wood", "wool", "word", "work",
            "world", "worry", "worth", "worthwhile", "would", "wound", "wrap", "wrath", "wreath", "wreck", "wrestle",
            "wrist", "write", "wrong", "yard", "year", "yearly", "yellow", "yesterday", "yield", "young", "youth",
            "zebra", "zesty", "zone", "zoo"
        };

        public static readonly (string mnemonic, string seed, string expectedMasterPrvKey)[]_vectors = new[]
        {
            (
                "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
                "alice",
                "4b4553984228b22fa5bfe1f2b8b6a7b3aba4d1e5f9c9c3b9f3c1a7b8c9d0e1f2"
            )
        };
    }

    public static class Tron
    {
        public static readonly (string privateKeyHex, string expectedAddress)[] AddressVectors = new[]
        {
            (
                "25E9F2EDAAF9464E9FA0EFDB896835741EBE0F5E34F97CFB88457818B6681C32",
                "TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9"
            ),
            (
                "0000000000000000000000000000000000000000000000000000000000000001",
                "THDnARhK6LWt4q4k2rTN3sYbZA9RFbFkvN"
            ),
            (
                "0000000000000000000000000000000000000000000000000000000000000002",
                "TYzctaL5sCGGJXmMXANsYcNtyzV2c4wMh8"
            ),
        };

        public static readonly (string mnemonic, string passphrase, string expectedAddress)[] HdWalletVectors = new[]
        {
            (
                "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
                "alice",
                "TRwLVA7uP3aYbw3BXURx4emRobdV7aTrX7"
            )
        };
    }
}
